httpwg/http2-spec

- draft-ietf-httpbis-http2.xml
> Clarifying idle stream priority

- draft-ietf-httpbis-http2.xml
> Adding DoS considerations for CONNECT

- draft-ietf-httpbis-http2.xml
> Proper scope limitation on extension section

- draft-ietf-httpbis-http2.xml
> Reset of promised stream for unsafe method clarifications

- draft-ietf-httpbis-http2.xml
> HTTP/2 doesn't enable compressed content-codings

- draft-ietf-httpbis-http2.xml
> Scrubbing for the use of 'optional'

- draft-ietf-httpbis-http2.xml
> PRI is safe and idempotent

- draft-ietf-httpbis-http2.xml
> Changes from Alissa Coopers IESG review

- draft-ietf-httpbis-http2.xml
Dealing with the DISCUSS and a few comments.
> Spencer Dawkins' IESG review feedback

- draft-ietf-httpbis-http2.xml
This isn't everything yet, but it's the easy ones.
> De-MUST-ifying for Pete Resnick

- draft-ietf-httpbis-http2.xml
Fixes for those things that were obviously busted.  Which (I hope) addresses the comments, with one exception (Richard's discuss contained suggested edits that should clear that one up).
> Edits just for Stephen Farrell

- draft-ietf-httpbis-header-compression.xml
This is a minimal proposal for solving #728.
> Clarify dynamic table maximum size evolution.

- draft-ietf-httpbis-http2.xml
This makes it clearer that they can't be sent otherwise.
Closes #726
> PUSH_PROMISE sending conditions

- draft-ietf-httpbis-http2.xml
> Noting effect of settings on flow control more precisely

- draft-ietf-httpbis-http2.xml
After some sleep, I've read through the section and noticed a few other minor inconsistencies.  This alters the structure slightly, as well as replacing the first sentence with a more accurate one.
Supercedes #732.  Closes #731, #732.
> Goaway fix v2

- draft-ietf-httpbis-http2.xml
> Headers are OK in 'idle'

- draft-ietf-httpbis-http2.xml
> Adding protection from padding for the fields in HEADERS

- draft-thomson-httpbis-http2bis.xml
Wherein I sign a deal with the devil.
> Adding myself as editor

- .editorconfig
- draft-thomson-httpbis-http2bis.xml
This didn't help a lot with pull requests in QUIC, but it did help people who made regular contributions.
> Add .editorconfig

- draft-thomson-httpbis-http2bis.xml
> Defer to the core spec for connection-specific headers

- draft-thomson-httpbis-http2bis.xml
> Extensions defining pseudo-header fields

- draft-thomson-httpbis-http2bis.xml
> Condition SNI requirement more carefully

- draft-ietf-httpbis-http2bis.xml
> Reduce the width of the upgrade diagram.

- draft-ietf-httpbis-http2bis.xml
> fix IETF working group name

- draft-ietf-httpbis-http2bis.xml
> Clarify error handling when multiple errors are encountered.

- draft-ietf-httpbis-http2bis.xml
(there are more nits like missing DOIs etc, but let's do this one by one)
> references: IETF series should be first

- draft-ietf-httpbis-http2bis.xml
> Server Push caveats

- draft-ietf-httpbis-http2bis.xml
> Partially-valid request/response handling

- draft-ietf-httpbis-http2bis.xml
> Copy the QUIC text regarding generic errors

- draft-ietf-httpbis-http2bis.xml
This is going to conflict with other changes, but that's just how things roll around here.
> Remove dead references

- draft-ietf-httpbis-http2bis.xml
Not sure that this needs a citation.
Closes #785.
> Remote timing attacks are a thing

- draft-ietf-httpbis-http2bis.xml
Brought over the QUIC text about flow control performance.
cc @wtarreau
Resolves #784.
> Discuss flow control performance

- draft-ietf-httpbis-http2bis.xml
> Clean closed state

- draft-ietf-httpbis-http2bis.xml
> Discuss invalid field names and values

- draft-ietf-httpbis-http2bis.xml
> Mark HTTP2-Settings obsolete properly

- draft-ietf-httpbis-http2bis.xml
These will be good for about 2 days based on what I'm seeing now, but I
can just update to -17 then.
> Update core drafts references

- draft-ietf-httpbis-http2bis.xml
Julian identified one.  I found a few more.
Closes #886.
> Mostly just fields

- draft-ietf-httpbis-http2bis.xml
> Make introduction more objective

- draft-ietf-httpbis-http2bis.xml
Thanks @wtarreau for find this little discrepancy.
> Use absolute-path

- draft-ietf-httpbis-http2bis.xml
> Avoid previous versions, use RFC7540

- draft-ietf-httpbis-http2bis.xml
> Just one missing title case flag name

- draft-ietf-httpbis-http2bis.xml
Fixes #927 by copying the text from DATA
> Padding text on HEADERS

- draft-ietf-httpbis-http2bis.xml
Nits through Section 7; more to follow.
> Nits through S7

- draft-ietf-httpbis-http2bis.xml
> Contains is not set

- draft-ietf-httpbis-http2bis.xml
> Revise overview text on priority

- draft-ietf-httpbis-http2bis.xml
> Clarify the rules on server-sent HEADERS

- draft-ietf-httpbis-http2bis.xml
> Prohibit duplicate pseudo-headers.

- draft-ietf-httpbis-http2bis.xml
> Drop redundancy in :authority translation

- draft-ietf-httpbis-http2bis.xml
> Ciphers were listed in 2015.

- draft-ietf-httpbis-http2bis.xml
> Remove content-length from the chunked example

- draft-ietf-httpbis-http2bis.xml
> No path for CONNECT

- draft-ietf-httpbis-http2bis.xml
I know that Cory beat me to it with #947, but I had written text.  I only forgot to make the PR.  Cory can decide which he likes better :)
Closes #941.
> reference extended connect

- draft-ietf-httpbis-http2bis.xml
Followup for #953.
Closes #948.
> Fixup IANA links

- draft-ietf-httpbis-http2bis.xml
> Make obsoleted registrations consistent

- draft-ietf-httpbis-http2bis.xml
Covers #878 in tandem with #879.
> Clarify who may send PUSH_PROMISE frames

- draft-ietf-httpbis-http2bis.xml
Includes changes from #970, as that hits the same paragraph.
> Registry names

- draft-ietf-httpbis-http2bis.xml
We cite it and attach normative language to it.
For #974.
> TLS BCP is normative

- draft-ietf-httpbis-http2bis.xml
> Cite error code section

- draft-ietf-httpbis-http2bis.xml
> Cite deprecation note

- draft-ietf-httpbis-http2bis.xml
> Fix sections format

- draft-ietf-httpbis-http2bis.xml
> Add citation for odd request forms

- draft-ietf-httpbis-http2bis.xml
> Keep the note about updating stuff

- draft-ietf-httpbis-http2bis.xml
> Reference is to this doc

- draft-ietf-httpbis-http2bis.xml
> Settings are acknowledged in order

- draft-ietf-httpbis-http2bis.xml
And an update to the section reference.
For #990.
> More explanation about no content responses

- draft-ietf-httpbis-http2bis.xml
This is confusing; hopefully this rewrite is a little less so.
For #990.
> PUSH_PROMISE and SETTINGS_MAX_CONCURRENT_STREAMS

- draft-ietf-httpbis-http2bis.xml
Important enough to note in the change log anyway.
> Updates to -semantics are important

- draft-ietf-httpbis-http2bis.xml
Add a definition for SETTING contents.
Add a forward reference to the changes section.
> Roman's review

- draft-ietf-httpbis-http2bis.xml
> Editorial suggestions from Benjamin Kaduk's IESG Evaluation

- draft-ietf-httpbis-http2bis.xml
Consistency is the hobgoblin of small minds and all that.
Closes #1008.
> In units of octets

- draft-ietf-httpbis-http2bis.xml
I'll need to respond via email, but these changes all seem fine.  I'm less sure about the first one than the others though, so look at that carefully.  I'm equally happy pushing back on that; Sean is right that this is probably the most important factoid in the text, but the reordering is a little awkward.
> Sean's SECDIR review

- draft-ietf-httpbis-http2bis.xml
> HTTP2-Settings status is obsoleted, not standard

- draft-ietf-httpbis-http2bis.xml
Fix up a typo reported by @Dev1an
> Clean up minor typo

- draft-ietf-httpbis-http2bis.xml
> Fix list construction for frame size error

- draft-ietf-httpbis-http2bis.xml
> "as" means "because"

- draft-ietf-httpbis-http2bis.xml
> Remove redundant Reserved field description from PUSH_PROMISE

- draft-ietf-httpbis-http2bis.xml
> GOAWAY is what is sent here

- draft-ietf-httpbis-http2bis.xml
> cookies using ; prevents use of multiple field lines

- draft-ietf-httpbis-http2bis.xml
> Let's cite both

- draft-ietf-httpbis-http2bis.xml
> Add a missing "that"

- draft-ietf-httpbis-http2bis.xml
> PUSH_PROMISE contains request control data and a header section

- draft-ietf-httpbis-http2bis.xml
> "as" means "because" here too

- draft-ietf-httpbis-http2bis.xml
> Remove SNI abbreviation

- draft-ietf-httpbis-http2bis.xml
> Use `<tt>` for content-length

- draft-ietf-httpbis-http2bis.xml
> Simplify greater state commitment sentence

- draft-ietf-httpbis-http2bis.xml
> Remap priority label

- draft-ietf-httpbis-http2bis.xml
> Simpler signaling

- draft-ietf-httpbis-http2bis.xml
> A tranche of consistency fixes

- draft-ietf-httpbis-http2bis.xml
The date will probably be June something, but let's worry about that
later.
> Last minute editorial stuff
