httpwg/http2-spec

- draft-ietf-httpbis-http2.xml
> Changed Incorrect "an" to "and" (Editorial)

- draft-ietf-httpbis-http2.xml
The current text says that you can receive a PUSH_PROMISE on an idle stream, which I don't believe was ever the intent.  Clarifying that PUSH_PROMISE references an idle stream in the Promised Stream ID field, and is not actually sent on the idle stream.
> No PUSH_PROMISE in idle

- draft-ietf-httpbis-http2.xml
Two issues were raised about the use of the words "existing" and "current" to refer to streams.  These were a little squishy, so I tightened the language a little.  The text no longer uses either word to refer to streams, instead using stream states to describe where the relevant text applies and favouring "identified" as a fallback.
> Identifying streams more precisely

- draft-ietf-httpbis-http2.xml
There were lots of small changes as a result of [the GenART review](http://www.ietf.org/mail-archive/web/gen-art/current/msg11211.html).
The only change of note is <https://github.com/http2/http2-spec/commit/d4e9ba3d57cb4c5a1a990a4e838369c37a7dad5d>, which adds text on what a receiver should expect and what they are obligated to do for streams in the "half closed (local)" state.
> Addressing GenART review comments

- draft-ietf-httpbis-http2.xml
Proposal to replace #696.  I think that this is a little clearer this way.
Also, it's strange that this was not added earlier, but then sometimes the most obvious things get missed.
cc @RobbySimpson
> Adding a failure note for decompression failure

- draft-ietf-httpbis-http2.xml
Kathleen Moriarty's IESG review noted some confusion that I think derived from the use of the word "prohibited" in relation to the cipher suite black list.
> Framing cipher suite prohibitions as a black list

- draft-ietf-httpbis-http2.xml
Moves considerations of defining an ALPN token for a non-TLS-based protocol to 3.1.
Changes "token" to "protocol identifier" in 3.3.
> Alternative to #703

- draft-ietf-httpbis-header-compression.xml
Expands section 7.1.3 to describes characteristics of header needing the protection offered by the never indexed literal representation.
> Expands never indexed literals guidance.

- draft-ietf-httpbis-http2.xml
This was confusing a few people who weren't clear if the prohibition on frame sending for CONTINUATION trumped this or not.  This isn't a perfect fix, but it should be enough.
> 'at any time' for PRIORITY was confusing people

- draft-thomson-httpbis-http2bis.xml
This patch also changes our text to be consistent in using "frame
payload" as a two-word phrase.
Note that this patch now sometimes leaves us with the text "frame payload of an X frame". Shout if that seems too clumsy and I can remove the last word "frame", though I think it has the advantage of being extremely clear.
Resolves #803.
> Remove use of "payload" for message bodies.

- draft-thomson-httpbis-http2bis.xml
A lot has happened to TLS since we did RFC 7540.  This tries to capture
that succinctly.
- It rolls in changes from RFC 8740.
- It mentions early data and RFC 8470.
- It updates references, citing TLS 1.3 rather than 1.2 for a generic
TLS reference.
Closes #774.
> Changes for TLS 1.3

- draft-thomson-httpbis-http2bis.xml
Make it clearer that midders leads to the message being invalid.  I
hope.  It was already pretty clear.
I did have to fix the definition for malformed requests, which was
missing.
And no mention was made of pseudo-header fields.
This uses new terminology too.  That might save effort in a larger
cleanup.
Closes #780.
> Clarifications for trailers

- draft-ietf-httpbis-http2bis.xml
This is a first stab at #759. I've gone for a minimal change here, simply clarifying that only HEADERS and PUSH_PROMISE frames have the effect of implicitly closing streams.
While I was writing this I did have a question that may need to be raised on-list: do HEADERS and PUSH_PROMISE only implicitly close streams if they are _accepted_? That is, if a client sends a HEADERS frame that triggers a stream error, does that HEADERS frame still implicitly close all streams with a lower stream ID that are in the "idle" state? This may also be worth clarifying.
> Clarify that PRIORITY does not close streams.

- draft-ietf-httpbis-http2bis.xml
The name of the wg is "HTTP Working Group" or just "HTTP". The data tracker abbreviation is httpbis.
> Correct WG name

- draft-ietf-httpbis-http2bis.xml
This is fairly cursory at this stage.  The goal is to get the document
functional first.  Next step is a full read-through for terminology.
> First pass on references to updated documents

- draft-ietf-httpbis-http2bis.xml
Why these were not already is a mystery not worth investigating.  Fix it
instead.
Closes #777 while we're at it.
> The core drafts are normative references

- draft-ietf-httpbis-http2bis.xml
After carefully reviewing the Netflix advisories, it was clear that the
problem was that implementations didn't read the original text.
The TCP window reduction attack in CVE-2019-9517 was not mentioned, and
it is a clever exploit.  The rest were clearly already documented.
I took the opportunity to restructure things a little bit.  The first
few CVEs were about causing the victim to enqueue a bunch of frames and
then exploit the fact that this queuing was badly inefficient.  Those
got a list of their own.
I purposefully left CVE-2019-9516 out.  Though I am sad that people
didn't free() after malloc(), this is pretty much just a systematized
memory leak and I don't feel like calling that out in an RFC.  I've
cited the disclosure page, so I think we're covered there anyway.
Closes #775.
> Speak more about DoS

- draft-ietf-httpbis-http2bis.xml
- draft-thomson-httpbis-http2bis.xml
The thinking has evolved considerably since the original reference was
made.  This is the right way to refer to this concept.
Closes #771.
> Reference RFC 6973 for fingerprinting

- draft-ietf-httpbis-http2bis.xml
That is, in text we added.
I have an open question to rfc-interest@ regarding correcting the spelling of author names in references.  It's pretty clear [what Bodo thinks](https://www.bmoeller.de/) about the mangling we have done to his name in pursuit of ASCII and I'd like to correct that.  I didn't see any others that would appear in the final document (Hervé is there too, but only first initials survive).
Closes #791.
> Hervé was the only one

- draft-ietf-httpbis-http2bis.xml
I think that this is better, but I'd like input on that.
I've tried to simplify this into 3 chunks:
* requests generated natively in HTTP/2
* translating HTTP/1.1 -> HTTP/2
* translating HTTP/2 -> HTTP/1.1
I realized that absolute-form was underserved here.  I could have
excluded it on the basis that it is special, but the rules seemed fairly
clear - at least regarding :authority, so that went in too.
The text now deals more fully with absolute form.  The previous text
really only hinted at the possibility that there might be two values.
This points to -messaging for what to do about those two values (hint:
:authority wins).
Closes #828.
> Rewrite :authority description

- draft-ietf-httpbis-http2bis.xml
The previous text implied that a value of 1 was a problem,
which was somewhat in tension with the default being 1 and servers
mostly not sending the setting.  So clearly what was being checked by
client was the frame, not the value.  This changes to checking the
setting as it arrives, changes where that text lives.
Also, this changes from "endpoint" to "client" or "server" as
appropriate to match actual practice.
Closes #793.
> SETTINGS_ENABLE_PUSH from the server

- draft-ietf-httpbis-http2bis.xml
This is either taken from the target URI, or translated in (S3.3 of
-messaging).  Unless it is CONNECT where is is absent.
Closes #831.
> :scheme is just the scheme

- draft-ietf-httpbis-http2bis.xml
> Remove "parameters" from the IANA registry name

- draft-ietf-httpbis-http2bis.xml
The current rules state that you need to include text in abstract and
introduction.
This will result in redundant entries for the specs with other changes that add 7540 references, but we can sort that out later. 
Closes #842.
> Do the obsoletes thing properly

- draft-ietf-httpbis-http2bis.xml
xml2rfc is overly pedantic about non-ASCII text.  The result in this
case was that Hervé's name was being mangled to include a literal
`&#233;`, even in a text format (where HTML character references make no
sense).  To avoid that, this is what is necessary.  Of course, this
makes the rendering of the document with the RFC Editor stylesheet look
awful.  I've decided not to concern myself with that part though; the
stylesheet we use is fine.
> xml2rfc workaround

- draft-ietf-httpbis-http2bis.xml
In the spirit of the naming simplications of the recent HTTP changes, we
can talk about settings in this revision.
This aligns better with HTTP/3, though that still uses "settings
parameters" (with that ugly double-plural).
cc @MikeBishop
> Stop using "settings parameters"

- draft-ietf-httpbis-http2bis.xml
This required a little careful rewriting of text that only recently
rewrote.  Hopefully this retains the improvements of that rewrite.
Closes #841.
> Make HTTP/1.1 reference informational

- draft-ietf-httpbis-http2bis.xml
This doesn't completely remove it, but it only keeps those pieces
necessary for interoperability with existing implementations: the rules
for sending PRIORITY frames in different stream states, the format of
the HEADERS and PRIORITY frames, and the error handling.
It replaces the exposition about how priority works with a deprecation
notice and the little advice that we currently understand to be
accurate.
Closes #773.
> Remove priority

- draft-ietf-httpbis-http2bis.xml
HTTP/1.1 to HTTP/2 Upgrade was never widely deployed and has no
particular defenders. This change removes the text explaining and
defining the mechanism.
Resolves #772.
This change still requires discussion on the mailing list.
> Remove Upgrade mechanism.

- draft-ietf-httpbis-http2bis.xml
Here is some draft text. In principle we don't need any of this at all: as this text shows, all of the relevant guidance is already present in both semantics and H2. I've elected to throw up some possible text, but if we wanted to say that some or all of it is entirely redundant with existing specifications then I'm happy to do so.
Fixes #789.
Fixes #851.
> Add details regarding removal of connection-specific fields.

- draft-ietf-httpbis-http2bis.xml
This is part of the fix for #826.  This part removes the experimental range for frame types and settings.
Also updates to use section references to RFC 8126, which replaces RFC 5226.
> Experimental begone

- draft-ietf-httpbis-http2bis.xml
This encodes the conclusions from interim discussions:
1. CR, LF, and NUL cannot appear anywhere in field names or values.
2. SP and HTAB cannot appear at the start or end of field names or
values.
3. COLON cannot appear anywhere in a field name, except for the colon at
the start of a pseudo-header field name.
The strong requirements about validating fields according to ABNF has
been replaced.
The text is clearer about how the pieces fit together: it is HPACK that
allows any octet, whereas HTTP/2 makes certain choices invalid.
Closes #815.
> What characters are permitted

- .gitignore
- draft-ietf-httpbis-http2bis.xml
The validation for uppercase characters is no longer listed separately, but instead included with the minimal validation.
> Improve on fix for #815 for lowercase validation

- draft-ietf-httpbis-http2bis.xml
The only change we have planned for the draft that isn't in the change
log yet.
Captures #865 changes, whether that is via #866 or other changes, the
substance of the change is roughly the same.
Closes #852.
> Change log for character validation

- draft-ietf-httpbis-http2bis.xml
Now without the "e" too.
For this revision I would consider Mark Nottingham, Willy Tarreau, and
Greg Wilkins for direct acknowledgment, but as they are all listed in
RFC 7540 it seems safer to avoid specific mentions here.
Closes #862.
> A leaner acknowledgments section

- draft-ietf-httpbis-http2bis.xml
Though I had to be careful with text on TCP, which has FIN and RST bits
we don't want to touch.
> A simple, but manual, s/bit \d/the XXX Flag/

- draft-ietf-httpbis-http2bis.xml
RFC 4492 is obsolete.
This is a TLS 1.2 section, so it is OK to refer to the TLS 1.2 document here.
> Update ECC reference

- draft-ietf-httpbis-http2bis.xml
...that is frame formats.
I've chosen to put blank lines before and after both frames and the
stream identifier part of the stream header.  That should make this a
lot clearer.
@wtarreau was right that this was a little hard to process without that.
Hopefully this is a tiny bit better.
> Add some structure to the undifferentiated mess

- draft-ietf-httpbis-http2bis.xml
fixes #896
The old text stated padding things were identical to DATA frames. That might not be
entirely true. ﻿So just spell out the requirements expicitly.
> Explicitly state HEADERS and PUSH_PROMISE padding reqs

- draft-ietf-httpbis-http2bis.xml
And correctly refer to the trailer section.
Closes #900.
> Improve list construction

- draft-ietf-httpbis-http2bis.xml
Which changes
> Extensions are permitted to use new frame types (Section 4.1), new settings (Section 6.5.2), or new error codes (Section 7).
to
> Extensions are permitted to use new frame types (Section 4.1), new settings (Section 6.5), or new error codes (Section 7).
> extending H2: make ref to settings more generic

- draft-ietf-httpbis-http2bis.xml
I believe the rule in #918 is supposed to be that the layout diagrams use "FOO Flag", while the prose uses "the FOO flag."  If so, this lowercases some other instances.
> Lowercase "flag" when not in frame artwork

- draft-ietf-httpbis-http2bis.xml
We could try to make every statement precise.  We could add "of the
frames defined in this document" to a bunch of places.  Or we could make
a (better) blanket statement.  That is what this does.
Closes #915.
> More regarding erratum 6309

- draft-ietf-httpbis-http2bis.xml
As stated in #903, it's misleading and contradictory.  Better to
concentrate on configuration for this, as that is the common usage.
Closes #903.
> Avoid mention of Alt-Svc for h2c

- draft-ietf-httpbis-http2bis.xml
... or the analysis in the security considerations.
We had to walk a more careful path when RFC 7540 was published, so we were careful to legitimize h2c.  In the years since, things have changed and we can be more direct.  This isn't a "don't use h2c", but more of a disclaimer as far as security goes.
> h2c really isn't covered by security promises

- draft-ietf-httpbis-http2bis.xml
The original issue here was concerned with Transfer-Encoding, but this
was not a normative statement, it was a note.  With a forward reference,
this is better.
The section on connection-specific headers probably could have been more
specific.  Now that the -semantics draft has a specific list of things
(plus whatever `Connection` lists), we can lean on that more directly.
Closes #938.
> More on connection-specific headers

- draft-ietf-httpbis-http2bis.xml
This text wasn't actually changed in #933, but I noticed it while reviewing.  This says that implementations which support TLS MUST use ALPN, but that's not really tied to what the implementation supports -- it's tied to what the current connection is doing.  If you support TLS but are using cleartext TCP for the current connection (regardless of why), you're not required to use ALPN.
> Connections, not implemenations

- draft-ietf-httpbis-http2bis.xml
This removes the "from another HTTP version" and just uses "forwards"
with "to" or "from".  Not sure if that helps.
The rest is an attempt to tighten things up.
Closes #913.
Closes #935 (as this supersedes it).
Closes #912.
> Tighten forward language

- draft-ietf-httpbis-http2bis.xml
This just moves the reference to the canonical definition of what is
valid up to the top of the section.  That's the canonical text.
This emphasizes the point that HTTP/2 is placing *additional*
requirements on endpoints with respect to validation.
This does not really fix #902 in the sense that it leaves validation of
DQUOTE and friends to the core semantics implementations.
Note that any "MAY" requirement for rejecting a messaging can have the
desired effect on those generating those messages: if an endpoint puts
DQUOTE in a field name, that message will have little hope of being
successfully handled.
Closes #902.
> Move field validation text around

- draft-ietf-httpbis-http2bis.xml
Only pseudo-header fields can be mandatory, so no point saying anything
about fields more generally here.
Closes #962.
> No fields are mandatory

- draft-ietf-httpbis-http2bis.xml
Just state it. No need to justify it so (especially as this invites
questions about the claimed benefits).
This is less than Julian wanted from #963, but I think that it is
important to include a requirement like this very clearly and it isn't
really said anywhere else.  At least not directly.
Closes #963.
> Don't justify lowercase requirement

- draft-ietf-httpbis-http2bis.xml
> Editorial suggestion

- draft-ietf-httpbis-http2bis.xml
This makes a few changes, restricting things further than before.  For
the most part, this removes an allowance in the original specification
that had Host and :authority potentially differing.  The goal of that
was - from memory - to preserve some of the inherent quirks in HTTP/1.1.
That turns out to be more of a liability than an asset and far less
important now that we have a more formal understanding of the structure
of requests.
Closes #905.
> Host and :authority must agree

- draft-ietf-httpbis-http2bis.xml
A recent xml2rfc update changed the way that the `<tt>` element was
rendered in text.  Take advantage of that by adding quotes to strings
that really do benefit from additional quoting, such as the "PRI ..."
preface string.
Most of the changes shown in a recent diff are down to losing quotes
on header field names and other protocol elements.  These do not need
to be quoted for their meaning to be clear and unambiguous.  The use
of `<tt>` for these items improves the HTML rendering, but the loss of
line noise in text renderings is a net win (at least in my opinion).
> Manually add quotes to important strings

- draft-ietf-httpbis-http2bis.xml
Partially addresses some of #974. This is the low hanging fruit.
> First pass cleaning up some of the typos from AD review

- draft-ietf-httpbis-http2bis.xml
This links to the section rather than the registry as we no longer list
frame types in the IANA considerations section.
For #974.
> Link to frame type definitions.

- draft-ietf-httpbis-http2bis.xml
Editorial change only.  The idea is to read as soon as data arrives in
the TCP buffer.
In practice, this is not necessary, but leaving things in the TCP buffer
indefinitely can deadlock.  (Some implementations of over TCP-based
protocols do this and in this case it is BAD.)
For #974.
> Fix the flow control text

- draft-ietf-httpbis-http2bis.xml
Two paragraphs up we mandate the use of PROTOCOL_ERROR, so this is not
necessary.
For #974.
> Remove contradictory text on use of RST_STREAM

- draft-ietf-httpbis-http2bis.xml
This isn't TCP RTT based.
For #990.
> Add a note about SETTINGS_TIMEOUT

- draft-ietf-httpbis-http2bis.xml
> Add mention of silly window syndrome

- draft-ietf-httpbis-http2bis.xml
A consequence of bad rendering logic, methinks.
Noted in #990.
> Fix bad reference to 400 (Bad Request)

- draft-ietf-httpbis-http2bis.xml
Mentioning RFC 7540 directly makes it clearer, I think.
From #990.
> Change title of priority background section

- draft-ietf-httpbis-http2bis.xml
This is the one case in Jörg's review where I think we need text.  In
the other places, the text is secondary to other normative language and
should not be restated in direct terms (or it would need to be far more
precise than it is).
For #990.
> 2119 language for second GOAWAY

- draft-ietf-httpbis-http2bis.xml
I improved the text along the lines Jörg suggested.  However, I realized
that the transition should really be in the diagram.  That's basically
impossible given the nature of the diagram, but it's worth including in
the description at least.
For #990.
> "idle"->"closed" transition

- draft-ietf-httpbis-http2bis.xml
As they relate to changes in SETTINGS_HEADER_TABLE_SIZE.
This is the strict, by-the-book interpretation.  That is, if the value
changes, you have to send the update, even if it is pointless (that is,
you aren't changing the size of the table).
Note that I'm eliding the point about multiple instructions, which are
necessary if the decoder reduces the maximum below the current size.
The only nod in that direction is "at least one" and a reference to the
section that talks about the need for multiple updates.
This pulls in more of RFC 7541 than I might have liked, but we have to
deal with the integration somewhere and this seems like a reasonable
place to do that.  It might have been better to put this text in a -bis
revision of RFC 7541, but we decided to leave that document as-is.
> Stricter, clearer rules for Dynamic Table Size Update

- draft-ietf-httpbis-http2bis.xml
This stems from the IESG review of the priorities draft, where Éric Vyncke noted the inconsistenc between prose and diagram. This change to use 0x throughout makes it consistent with HTTP/3, which helps documents that need to define frames for both versions.
> Add 0x to Frame layout diagrams for consistency

- draft-ietf-httpbis-http2bis.xml
Tweaked the mention of h2c to avoid describing it with much depth.
Clarified "both types of flow control".
Express that there's only one valid length for PING frames.
Add a reference to the TLS Ciphers section from Appendix A.
> Éric Vyncke's feedback.

- draft-ietf-httpbis-http2bis.xml
draft-ietf-httpbis-messaging is now going to be known as "HTTP/1.1".
Follow suit.
> Shorter name

- draft-ietf-httpbis-http2bis.xml
It's going to happen anyway, but we can at least warn people.
This doesn't specify what validation is necessary in any detail (that is
somewhat involved), it only notes that simple concatenation is almost
certainly not secure.
Closes #1015.
> Add some warnings about concatenation of URI parts

- draft-ietf-httpbis-http2bis.xml
This reverts commit 290e381719b2fefe4e6182d3be288c48e8f5fd7e.
See #1003 for most of the discussion.
The key change here is to address #1004 by only requiring that the change be signaled when the table size is reduced.  When I dug more into this, it's a more disruptive change, so I've made a bunch of additional changes in support of that.
> Stricter, clearer rules for Dynamic Table Size Update v2

- draft-ietf-httpbis-http2bis.xml
This change was lost in a major refactoring of the section accidentally.
Restore that.
> Restore change to Experimental Use policies

- draft-ietf-httpbis-http2bis.xml
We decided to do this for QUIC and it does improve readability and
consistency.
I did this manually, rather than trying to be clever with regexs.  I'd
appreciate a second pair of eyes.
I searched for `0x[0-9a-f](?:[0-9a-f]{2})*[^0-9a-f]` and found nothing;
same for `0x[0-9a-f]*[A-F][0-9a-f]*` (in case we had stray uppercase
strings).
> Pad hexadecimal literals to even digits

- draft-ietf-httpbis-http2bis.xml
None of this stuff is used, but it causes some XML processors to go looking in places they shouldn't.
> Get rid of XML line noise

- draft-ietf-httpbis-http2bis.xml
This looks terrible, but it's the form that the RFC we cite uses (also,
RFC 1323).
Closes #1032.
> bandwidth * delay product

- draft-ietf-httpbis-http2bis.xml
I had to add `<tt>` to one use of :authority.
Closes #1040.
> Quote pseudo field names

- draft-ietf-httpbis-http2bis.xml
Values is correct in the first case, but the second should be "a value"
by which it means "any value".
Closes #1064.
> Values in the first; a value in the second

- draft-ietf-httpbis-http2bis.xml
This PR contains textual changes made by the RFC editors, along with a
couple of XML changes where they were uncontroversial or necessary for
the text. I left out any change the RFC editors made that conflicted
substatially with changes we made in response to their comments.
> Apply textual changes from RFC Editors

- .note.xml
- draft-ietf-httpbis-http2bis.xml
- rfc9113.xml
Mostly.
I didn't remove the width and height attributes from the SVG.  Removing
these causes the diagram to be stretched to fit, which is not at all
desirable (especially in the default stylesheet).
I restored Kazuho's name in the priority doc references and changed it
to use the allocated number of RFC 9218 for that doc.
I removed entities and used literals for the two &nbsp; instances in the
document (these are now &#xa0;).
I sorted the xi:include elements for references.
The file we got from the RFC editor included quoted values for URI
schemes and pseudo-header field names in the form: `<tt>":scheme"</tt>`.
This was not consistently applied.  I've gone with what we had:
`"<tt>:scheme</tt>"`.
This builds on top of the cleanup in #1102 as I have no interest in dealing with rebases over …
> XML changes

- draft-ietf-httpbis-http2bis.xml
I had to remove the <bcp14> tags from the BCP 14 text, but the tool
restored them.
Other than that, there is no difference in output in the text files that
this generates, so I'm going to say that this was successful.
The source has a ton of whitespace changes, but that seems to be all.
> Run the tool I used to clean RFC 9000 on this one
